<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sp</string>
		<string>cir</string>
		<string>ckt</string>
		<string>tech</string>
		<string>mat</string>
		<string>input</string>
		<string>mesh_in</string>
		<string>struct</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i:(^\.subckt|^\.macro))\b</string>
	<key>foldingStopMarker</key>
	<string>(?i:(^\.ends|^.endm))\b</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Spice</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^.*$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.spice</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=not)possible</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.untitled</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.untitled</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.untitled</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:(^\.(end|probe|tran|ac|op|dc|Solver)))\b</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:(^\.(print(\s+(tran|dc|ac))?)))\b\s+(.+)</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:(^[crlkg]\w*))\b(\s+\w+)?(\s+\w+)?(\s+(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?(?i:(meg|m|u|n|p|f|g|t|k))?)?</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:(^[Solver|#include|HeatSolverView|Atar]\w*))?</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:(^e\w*))\b(\s+\w+)?(\s+\w+)?(\s+\w+)?(\s+\w+)?(\s+(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?(?i:(meg|m|u|n|p|f|g|t|k))?)?</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:(^[vi]\w*))\b(\s+\w+)?(\s+\w+)?(\s+(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?(?i:(meg|m|u|n|p|f|g|t|k))?)?(\s+(?i:pwl|pulse|dc|ac))?</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:(^[xqmd]\w*|^\.(subckt|macro|ends|endm|)))\b((\s+\w+)*)</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?(?i:(meg|m|u|n|p|f|g|t|k))?[sS]?)\b</string>
					<key>name</key>
					<string>constant.numeric.spice</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:(^\.(options?|param)))\b\s+(?i:(jobcontrol|model|laser|optconn|fiber|photodiode|ind_source))?</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.variable.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\w+)\s*=</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.spice</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:^\.model)\b(\s+\w+)?(\s+\w+)?</string>
					<key>name</key>
					<string>keyword.other.spice</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\*.*</string>
					<key>name</key>
					<string>comment.line.spice</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.spice</string>
	<key>uuid</key>
	<string>E242A8E1-0584-49A3-A20D-F3FEC61359D8</string>
</dict>
</plist>
